# use the official Bun image
FROM oven/bun:1 AS base
WORKDIR /app

# Stage 1: Install dependencies
FROM base AS deps
COPY tiktak-monorepo/package.json tiktak-monorepo/bun.lock* tiktak-monorepo/yarn.lock* tiktak-monorepo/package-lock.json* ./
COPY tiktak-monorepo/frameworks/next/package.json ./frameworks/next/
COPY tiktak-monorepo/packages/shared/package.json ./packages/shared/
RUN bun install

# Stage 2: Prerelease (Source copy and Build)
FROM base AS prerelease
WORKDIR /app
# Copy ONLY the contents of tiktak-monorepo folder to /app root
# This effectively makes /app the monorepo root inside the container
COPY tiktak-monorepo/ .

# Copy dependencies from deps stage
# We do this AFTER copying source code to ensure node_modules are not overwritten
COPY --from=deps /app/node_modules ./node_modules
COPY --from=deps /app/frameworks/next/node_modules ./frameworks/next/node_modules
COPY --from=deps /app/packages/shared/node_modules ./packages/shared/node_modules

# Set environment variables for build time
ARG NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN
ENV NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN=$NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN
ARG NEXT_PUBLIC_S3_PREFIX
ENV NEXT_PUBLIC_S3_PREFIX=$NEXT_PUBLIC_S3_PREFIX
ARG NEXT_PUBLIC_ABLY_API_KEY
ENV NEXT_PUBLIC_ABLY_API_KEY=$NEXT_PUBLIC_ABLY_API_KEY
ARG GEMINI_API_KEY
ENV GEMINI_API_KEY=$GEMINI_API_KEY
ARG QSTASH_TOKEN
ENV QSTASH_TOKEN=$QSTASH_TOKEN
ARG QSTASH_CURRENT_SIGNING_KEY
ENV QSTASH_CURRENT_SIGNING_KEY=$QSTASH_CURRENT_SIGNING_KEY
ARG QSTASH_NEXT_SIGNING_KEY
ENV QSTASH_NEXT_SIGNING_KEY=$QSTASH_NEXT_SIGNING_KEY
ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL
ARG AWS_S3_ACCESS_KEY_ID
ENV AWS_S3_ACCESS_KEY_ID=$AWS_S3_ACCESS_KEY_ID
ARG AWS_S3_SECRET_ACCESS_KEY
ENV AWS_S3_SECRET_ACCESS_KEY=$AWS_S3_SECRET_ACCESS_KEY
ARG AWS_REGION
ENV AWS_REGION=$AWS_REGION
ARG AWS_S3_ENDPOINT
ENV AWS_S3_ENDPOINT=$AWS_S3_ENDPOINT
ARG AWS_S3_BUCKET_NAME
ENV AWS_S3_BUCKET_NAME=$AWS_S3_BUCKET_NAME

# Redis / Upstash
ARG UPSTASH_STORE
ENV UPSTASH_STORE=$UPSTASH_STORE
ARG UPSTASH_SESSION
ENV UPSTASH_SESSION=$UPSTASH_SESSION
ARG UPSTASH_REDIS_CACHE
ENV UPSTASH_REDIS_CACHE=$UPSTASH_REDIS_CACHE

# Axiom
ARG AXIOM_TOKEN
ENV AXIOM_TOKEN=$AXIOM_TOKEN
ARG AXIOM_ACTION_LOG_DATASET
ENV AXIOM_ACTION_LOG_DATASET=$AXIOM_ACTION_LOG_DATASET
ARG AXIOM_BACKGROUND_JOB_DATASET
ENV AXIOM_BACKGROUND_JOB_DATASET=$AXIOM_BACKGROUND_JOB_DATASET

# ZeptoMail
ARG ZEPTOMAIL_SMTP_PORT
ENV ZEPTOMAIL_SMTP_PORT=$ZEPTOMAIL_SMTP_PORT
ARG ZEPTOMAIL_FROM_EMAIL
ENV ZEPTOMAIL_FROM_EMAIL=$ZEPTOMAIL_FROM_EMAIL
ARG ZEPTOMAIL_FROM_NAME
ENV ZEPTOMAIL_FROM_NAME=$ZEPTOMAIL_FROM_NAME
ARG ZEPTOMAIL_API_KEY
ENV ZEPTOMAIL_API_KEY=$ZEPTOMAIL_API_KEY
ARG ZEPTOMAIL_SMTP_PASSWORD
ENV ZEPTOMAIL_SMTP_PASSWORD=$ZEPTOMAIL_SMTP_PASSWORD
ARG ZEPTOMAIL_MAIL_AGENT
ENV ZEPTOMAIL_MAIL_AGENT=$ZEPTOMAIL_MAIL_AGENT

# OAuth
ARG GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ENV GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
ARG FACEBOOK_CLIENT_ID
ENV FACEBOOK_CLIENT_ID=$FACEBOOK_CLIENT_ID
ARG FACEBOOK_CLIENT_SECRET
ENV FACEBOOK_CLIENT_SECRET=$FACEBOOK_CLIENT_SECRET
ARG APPLE_CLIENT_ID
ENV APPLE_CLIENT_ID=$APPLE_CLIENT_ID
ARG APPLE_CLIENT_SECRET
ENV APPLE_CLIENT_SECRET=$APPLE_CLIENT_SECRET

# Payment
ARG EPOINT_PUBLIC_KEY
ENV EPOINT_PUBLIC_KEY=$EPOINT_PUBLIC_KEY
ARG EPOINT_PRIVATE_KEY
ENV EPOINT_PRIVATE_KEY=$EPOINT_PRIVATE_KEY

# Ably (Server)
ARG ABLY_API_KEY
ENV ABLY_API_KEY=$ABLY_API_KEY

# Build the Next.js app 
WORKDIR /app/frameworks/next
RUN bun run build

# Stage 3: Release
FROM base AS release
WORKDIR /app

# Add runtime environment variables
ARG NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN
ENV NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN=$NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN
ARG NEXT_PUBLIC_S3_PREFIX
ENV NEXT_PUBLIC_S3_PREFIX=$NEXT_PUBLIC_S3_PREFIX
ARG NEXT_PUBLIC_ABLY_API_KEY
ENV NEXT_PUBLIC_ABLY_API_KEY=$NEXT_PUBLIC_ABLY_API_KEY
ARG GEMINI_API_KEY
ENV GEMINI_API_KEY=$GEMINI_API_KEY
ARG QSTASH_TOKEN
ENV QSTASH_TOKEN=$QSTASH_TOKEN
ARG QSTASH_CURRENT_SIGNING_KEY
ENV QSTASH_CURRENT_SIGNING_KEY=$QSTASH_CURRENT_SIGNING_KEY
ARG QSTASH_NEXT_SIGNING_KEY
ENV QSTASH_NEXT_SIGNING_KEY=$QSTASH_NEXT_SIGNING_KEY
ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL
ARG AWS_S3_ACCESS_KEY_ID
ENV AWS_S3_ACCESS_KEY_ID=$AWS_S3_ACCESS_KEY_ID
ARG AWS_S3_SECRET_ACCESS_KEY
ENV AWS_S3_SECRET_ACCESS_KEY=$AWS_S3_SECRET_ACCESS_KEY
ARG AWS_REGION
ENV AWS_REGION=$AWS_REGION
ARG AWS_S3_ENDPOINT
ENV AWS_S3_ENDPOINT=$AWS_S3_ENDPOINT
ARG AWS_S3_BUCKET_NAME
ENV AWS_S3_BUCKET_NAME=$AWS_S3_BUCKET_NAME

# Redis / Upstash
ARG UPSTASH_STORE
ENV UPSTASH_STORE=$UPSTASH_STORE
ARG UPSTASH_SESSION
ENV UPSTASH_SESSION=$UPSTASH_SESSION
ARG UPSTASH_REDIS_CACHE
ENV UPSTASH_REDIS_CACHE=$UPSTASH_REDIS_CACHE

# Axiom
ARG AXIOM_TOKEN
ENV AXIOM_TOKEN=$AXIOM_TOKEN
ARG AXIOM_ACTION_LOG_DATASET
ENV AXIOM_ACTION_LOG_DATASET=$AXIOM_ACTION_LOG_DATASET
ARG AXIOM_BACKGROUND_JOB_DATASET
ENV AXIOM_BACKGROUND_JOB_DATASET=$AXIOM_BACKGROUND_JOB_DATASET

# ZeptoMail
ARG ZEPTOMAIL_SMTP_PORT
ENV ZEPTOMAIL_SMTP_PORT=$ZEPTOMAIL_SMTP_PORT
ARG ZEPTOMAIL_FROM_EMAIL
ENV ZEPTOMAIL_FROM_EMAIL=$ZEPTOMAIL_FROM_EMAIL
ARG ZEPTOMAIL_FROM_NAME
ENV ZEPTOMAIL_FROM_NAME=$ZEPTOMAIL_FROM_NAME
ARG ZEPTOMAIL_API_KEY
ENV ZEPTOMAIL_API_KEY=$ZEPTOMAIL_API_KEY
ARG ZEPTOMAIL_SMTP_PASSWORD
ENV ZEPTOMAIL_SMTP_PASSWORD=$ZEPTOMAIL_SMTP_PASSWORD
ARG ZEPTOMAIL_MAIL_AGENT
ENV ZEPTOMAIL_MAIL_AGENT=$ZEPTOMAIL_MAIL_AGENT

# OAuth
ARG GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ENV GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
ARG FACEBOOK_CLIENT_ID
ENV FACEBOOK_CLIENT_ID=$FACEBOOK_CLIENT_ID
ARG FACEBOOK_CLIENT_SECRET
ENV FACEBOOK_CLIENT_SECRET=$FACEBOOK_CLIENT_SECRET
ARG APPLE_CLIENT_ID
ENV APPLE_CLIENT_ID=$APPLE_CLIENT_ID
ARG APPLE_CLIENT_SECRET
ENV APPLE_CLIENT_SECRET=$APPLE_CLIENT_SECRET

# Payment
ARG EPOINT_PUBLIC_KEY
ENV EPOINT_PUBLIC_KEY=$EPOINT_PUBLIC_KEY
ARG EPOINT_PRIVATE_KEY
ENV EPOINT_PRIVATE_KEY=$EPOINT_PRIVATE_KEY

# Ably (Server)
ARG ABLY_API_KEY
ENV ABLY_API_KEY=$ABLY_API_KEY

# Set ownership
RUN chown -R bun:bun /app

# Copy the standalone build
# In a monorepo, standalone output keeps the directory structure
COPY --from=prerelease --chown=bun:bun /app/frameworks/next/.next/standalone ./

# Copy static files to the correct nested location
COPY --from=prerelease --chown=bun:bun /app/frameworks/next/.next/static ./frameworks/next/.next/static
COPY --from=prerelease --chown=bun:bun /app/frameworks/next/public ./frameworks/next/public

EXPOSE 3000
USER bun

# Run the Next.js server from the correct deep path
ENTRYPOINT [ "bun", "frameworks/next/server.js" ]
